import type { Ejercicio } from '../../dominio/tipos'

/**
 * Hoja GYM — el split de 4 días, tal cual.
 * `esAncla` sale de la propia hoja: la nota técnica dice "TU LEVANTAMIENTO ANCLA".
 * `claveProgresion` enlaza con la hoja PROGRESION para precargar el peso de la semana.
 */
export const EJERCICIOS: Ejercicio[] = [
  {
    id: 1, nombre: "Calentamiento: 25 pechadas + movilidad de hombro", dia: 1, orden: 1,
    seriesPlan: null, repsPlan: "5 min", rpePlan: null, descansoSeg: null,
    notaTecnica: "Aquí van tus pechadas. No las hagas al despertar y otra vez en el gym.",
    esAncla: false, restriccion: null, claveProgresion: null,
  },
  {
    id: 2, nombre: "Press de banca con barra", dia: 1, orden: 2,
    seriesPlan: 4, repsPlan: "4-6", rpePlan: 8, descansoSeg: 180,
    notaTecnica: "TU LEVANTAMIENTO ANCLA. Este peso no baja durante el corte. Si baja 2 semanas seguidas, el déficit es muy agresivo.",
    esAncla: true, restriccion: null, claveProgresion: "pressBancaTope",
  },
  {
    id: 3, nombre: "Press inclinado con mancuernas", dia: 1, orden: 3,
    seriesPlan: 3, repsPlan: "8-10", rpePlan: 8, descansoSeg: 120,
    notaTecnica: "Inclinación 30°, no más.",
    esAncla: false, restriccion: null, claveProgresion: null,
  },
  {
    id: 4, nombre: "Fondos en paralelas", dia: 1, orden: 4,
    seriesPlan: 3, repsPlan: "8-10", rpePlan: 8, descansoSeg: 120,
    notaTecnica: "Lastrados si haces más de 12 limpias. Pecho ligeramente inclinado hacia adelante.",
    esAncla: false, restriccion: null, claveProgresion: null,
  },
  {
    id: 5, nombre: "Cruce de poleas (aperturas)", dia: 1, orden: 5,
    seriesPlan: 3, repsPlan: "12-15", rpePlan: 9, descansoSeg: 60,
    notaTecnica: "Aquí sí llegas cerca del fallo. Es aislamiento, es seguro.",
    esAncla: false, restriccion: null, claveProgresion: null,
  },
  {
    id: 6, nombre: "Extensión de tríceps en polea (barra recta)", dia: 1, orden: 6,
    seriesPlan: 3, repsPlan: "10-12", rpePlan: 8, descansoSeg: 90,
    notaTecnica: "Codos pegados al torso.",
    esAncla: false, restriccion: null, claveProgresion: null,
  },
  {
    id: 7, nombre: "Extensión sobre cabeza con cuerda", dia: 1, orden: 7,
    seriesPlan: 3, repsPlan: "12-15", rpePlan: 9, descansoSeg: 60,
    notaTecnica: "Trabaja la cabeza larga del tríceps — la que da volumen al brazo.",
    esAncla: false, restriccion: null, claveProgresion: null,
  },
  {
    id: 8, nombre: "Curl de muñeca con barra", dia: 1, orden: 8,
    seriesPlan: 3, repsPlan: "15-20", rpePlan: 9, descansoSeg: 45,
    notaTecnica: "Antebrazo. Rango completo, peso ligero.",
    esAncla: false, restriccion: null, claveProgresion: null,
  },
  {
    id: 9, nombre: "Paseo del granjero (farmer's carry)", dia: 1, orden: 9,
    seriesPlan: 3, repsPlan: "45 seg", rpePlan: 8, descansoSeg: 60,
    notaTecnica: "Agarre + antebrazo + core en un solo movimiento.",
    esAncla: false, restriccion: null, claveProgresion: null,
  },
  {
    id: 10, nombre: "Plancha frontal", dia: 1, orden: 10,
    seriesPlan: 3, repsPlan: "45-60 seg", rpePlan: 8, descansoSeg: 45,
    notaTecnica: "",
    esAncla: false, restriccion: null, claveProgresion: null,
  },
  {
    id: 11, nombre: "Dead bug con banda", dia: 1, orden: 11,
    seriesPlan: 3, repsPlan: "10/lado", rpePlan: 8, descansoSeg: 45,
    notaTecnica: "Anti-extensión. Sustituye la elevación de piernas: no carga el disco en flexión.",
    esAncla: false, restriccion: null, claveProgresion: null,
  },
  {
    id: 12, nombre: "CARDIO: 15 min Z2 en cinta o elíptica", dia: 1, orden: 12,
    seriesPlan: null, repsPlan: "15 min", rpePlan: null, descansoSeg: null,
    notaTecnica: "Frecuencia conversacional. No corras aquí — el correr largo va el sábado.",
    esAncla: false, restriccion: null, claveProgresion: null,
  },
  {
    id: 13, nombre: "Calentamiento: 2x8 dominadas + face pull ligero", dia: 2, orden: 1,
    seriesPlan: null, repsPlan: "5 min", rpePlan: null, descansoSeg: null,
    notaTecnica: "Aquí van tus dominadas. Meta: llegar a 25-50 acumuladas en la sesión sumando series.",
    esAncla: false, restriccion: null, claveProgresion: null,
  },
  {
    id: 14, nombre: "Dominadas lastradas", dia: 2, orden: 2,
    seriesPlan: 4, repsPlan: "5-8", rpePlan: 8, descansoSeg: 180,
    notaTecnica: "TU LEVANTAMIENTO ANCLA de tracción. Si no llegas a 5 lastradas, hazlas al peso corporal 4x8-10.",
    esAncla: true, restriccion: null, claveProgresion: "dominadas",
  },
  {
    id: 15, nombre: "Remo en máquina con pecho apoyado", dia: 2, orden: 3,
    seriesPlan: 4, repsPlan: "8-12", rpePlan: 8, descansoSeg: 150,
    notaTecnica: "TU LEVANTAMIENTO ANCLA de espalda: 5 discos de 45 lb por lado x12. El pecho apoyado quita la carga del erector lumbar — por eso reemplaza al remo con barra inclinado.",
    esAncla: true, restriccion: null, claveProgresion: "remoMaquina",
  },
  {
    id: 16, nombre: "Jalón al pecho agarre neutro", dia: 2, orden: 4,
    seriesPlan: 3, repsPlan: "10-12", rpePlan: 8, descansoSeg: 90,
    notaTecnica: "",
    esAncla: false, restriccion: null, claveProgresion: null,
  },
  {
    id: 17, nombre: "Remo en polea baja", dia: 2, orden: 5,
    seriesPlan: 3, repsPlan: "10-12", rpePlan: 8, descansoSeg: 90,
    notaTecnica: "Aprieta 1 segundo en la contracción.",
    esAncla: false, restriccion: null, claveProgresion: null,
  },
  {
    id: 18, nombre: "Face pull", dia: 2, orden: 6,
    seriesPlan: 3, repsPlan: "15-20", rpePlan: 9, descansoSeg: 60,
    notaTecnica: "Salud de hombro. No lo saltes — con este volumen de press lo vas a necesitar.",
    esAncla: false, restriccion: null, claveProgresion: null,
  },
  {
    id: 19, nombre: "Pájaros / elevación posterior", dia: 2, orden: 7,
    seriesPlan: 3, repsPlan: "15-20", rpePlan: 9, descansoSeg: 60,
    notaTecnica: "Deltoide posterior.",
    esAncla: false, restriccion: null, claveProgresion: null,
  },
  {
    id: 20, nombre: "Curl con barra Z", dia: 2, orden: 8,
    seriesPlan: 3, repsPlan: "8-10", rpePlan: 8, descansoSeg: 90,
    notaTecnica: "",
    esAncla: false, restriccion: null, claveProgresion: null,
  },
  {
    id: 21, nombre: "Curl martillo", dia: 2, orden: 9,
    seriesPlan: 3, repsPlan: "10-12", rpePlan: 8, descansoSeg: 60,
    notaTecnica: "También pega antebrazo (braquiorradial).",
    esAncla: false, restriccion: null, claveProgresion: null,
  },
  {
    id: 22, nombre: "Press Pallof en polea", dia: 2, orden: 10,
    seriesPlan: 3, repsPlan: "12/lado", rpePlan: 8, descansoSeg: 45,
    notaTecnica: "Anti-rotación. Reemplaza la rueda abdominal, que carga el disco en extensión bajo tensión.",
    esAncla: false, restriccion: null, claveProgresion: null,
  },
  {
    id: 23, nombre: "Paseo maleta (suitcase carry)", dia: 2, orden: 11,
    seriesPlan: 3, repsPlan: "40 seg/lado", rpePlan: 8, descansoSeg: 45,
    notaTecnica: "Anti-flexión lateral. Transfiere al swing de softball sin rotar la columna bajo carga.",
    esAncla: false, restriccion: null, claveProgresion: null,
  },
  {
    id: 24, nombre: "CARDIO: 15 min Z2", dia: 2, orden: 12,
    seriesPlan: null, repsPlan: "15 min", rpePlan: null, descansoSeg: null,
    notaTecnica: "",
    esAncla: false, restriccion: null, claveProgresion: null,
  },
  {
    id: 25, nombre: "A1 Press inclinado con mancuernas", dia: 3, orden: 1,
    seriesPlan: 4, repsPlan: "8-10", rpePlan: 8, descansoSeg: 0,
    notaTecnica: "Superserie con A2: no descansas entre A1 y A2.",
    esAncla: false, restriccion: null, claveProgresion: null,
  },
  {
    id: 26, nombre: "A2 Remo con mancuerna a una mano", dia: 3, orden: 2,
    seriesPlan: 4, repsPlan: "8-10/lado", rpePlan: 8, descansoSeg: 90,
    notaTecnica: "Descansas 90 s después de completar A1+A2.",
    esAncla: false, restriccion: null, claveProgresion: null,
  },
  {
    id: 27, nombre: "B1 Press militar de pie con barra", dia: 3, orden: 3,
    seriesPlan: 3, repsPlan: "6-8", rpePlan: 8, descansoSeg: 0,
    notaTecnica: "TU LEVANTAMIENTO ANCLA de hombro. De pie, no sentado.",
    esAncla: true, restriccion: null, claveProgresion: null,
  },
  {
    id: 28, nombre: "B2 Jalón al pecho agarre ancho", dia: 3, orden: 4,
    seriesPlan: 3, repsPlan: "10-12", rpePlan: 8, descansoSeg: 90,
    notaTecnica: "",
    esAncla: false, restriccion: null, claveProgresion: null,
  },
  {
    id: 29, nombre: "C1 Elevaciones laterales", dia: 3, orden: 5,
    seriesPlan: 3, repsPlan: "15-20", rpePlan: 9, descansoSeg: 0,
    notaTecnica: "Deltoide medio — el que da ancho a la silueta.",
    esAncla: false, restriccion: null, claveProgresion: null,
  },
  {
    id: 30, nombre: "C2 Pechadas hasta 2 reps del fallo", dia: 3, orden: 6,
    seriesPlan: 3, repsPlan: "máx", rpePlan: 9, descansoSeg: 60,
    notaTecnica: "Aquí completas el volumen de pechadas del día.",
    esAncla: false, restriccion: null, claveProgresion: "pechadas",
  },
  {
    id: 31, nombre: "Elevación frontal en polea", dia: 3, orden: 7,
    seriesPlan: 3, repsPlan: "12-15", rpePlan: 8, descansoSeg: 60,
    notaTecnica: "",
    esAncla: false, restriccion: null, claveProgresion: null,
  },
  {
    id: 32, nombre: "Encogimientos de trapecio", dia: 3, orden: 8,
    seriesPlan: 3, repsPlan: "12-15", rpePlan: 8, descansoSeg: 60,
    notaTecnica: "",
    esAncla: false, restriccion: null, claveProgresion: null,
  },
  {
    id: 33, nombre: "Bird dog", dia: 3, orden: 9,
    seriesPlan: 3, repsPlan: "10/lado", rpePlan: 7, descansoSeg: 40,
    notaTecnica: "Estabilidad lumbar. Lento, sin rotar la cadera.",
    esAncla: false, restriccion: null, claveProgresion: null,
  },
  {
    id: 34, nombre: "Plancha lateral", dia: 3, orden: 10,
    seriesPlan: 3, repsPlan: "40 seg/lado", rpePlan: 8, descansoSeg: 30,
    notaTecnica: "",
    esAncla: false, restriccion: null, claveProgresion: null,
  },
  {
    id: 35, nombre: "Calentamiento: bicicleta 8 min + movilidad cadera/tobillo", dia: 4, orden: 1,
    seriesPlan: null, repsPlan: "10 min", rpePlan: null, descansoSeg: null,
    notaTecnica: "La bicicleta antes de pierna no es opcional con menisco: calienta el líquido sinovial.",
    esAncla: false, restriccion: null, claveProgresion: null,
  },
  {
    id: 36, nombre: "Activación glútea con banda (puente + abducción)", dia: 4, orden: 2,
    seriesPlan: 2, repsPlan: "15", rpePlan: 6, descansoSeg: 30,
    notaTecnica: "Glúteo dormido = rodilla trabajando de más.",
    esAncla: false, restriccion: null, claveProgresion: null,
  },
  {
    id: 37, nombre: "Prensa de piernas", dia: 4, orden: 3,
    seriesPlan: 4, repsPlan: "6-8", rpePlan: 8, descansoSeg: 180,
    notaTecnica: "TU LEVANTAMIENTO ANCLA de pierna. Máximo 800 lb. NO bajes hasta que la pelvis se despegue del respaldo — ahí es donde se hernia.",
    esAncla: true, restriccion: null, claveProgresion: "prensaPiernas",
  },
  {
    id: 38, nombre: "Empuje de cadera con barra (hip thrust)", dia: 4, orden: 4,
    seriesPlan: 4, repsPlan: "8-10", rpePlan: 8, descansoSeg: 120,
    notaTecnica: "Cadena posterior principal. Carga el glúteo con la columna neutra y apoyada.",
    esAncla: false, restriccion: null, claveProgresion: "empujeCadera",
  },
  {
    id: 39, nombre: "Peso muerto rumano con barra hexagonal o mancuernas", dia: 4, orden: 5,
    seriesPlan: 3, repsPlan: "8-10", rpePlan: 7, descansoSeg: 120,
    notaTecnica: "",
    esAncla: false, restriccion: "CONDICIONAL — solo con autorización médica. Si no la tienes, sustituye por curl femoral sentado 4x12-15.", claveProgresion: "rdlHex",
  },
  {
    id: 40, nombre: "Extensión de cuádriceps", dia: 4, orden: 6,
    seriesPlan: 3, repsPlan: "12-15", rpePlan: 9, descansoSeg: 90,
    notaTecnica: "Stack completo (210 lb). Como ya lo maxeas: tempo 3 seg en la bajada y pausa de 1 seg arriba. Duele mucho más con el mismo peso.",
    esAncla: false, restriccion: null, claveProgresion: null,
  },
  {
    id: 41, nombre: "Curl femoral tumbado o sentado", dia: 4, orden: 7,
    seriesPlan: 4, repsPlan: "12-15", rpePlan: 9, descansoSeg: 75,
    notaTecnica: "Isquiotibial = estabilizador directo de la rodilla. Con menisco deteriorado esto es prevención, no accesorio.",
    esAncla: false, restriccion: null, claveProgresion: null,
  },
  {
    id: 42, nombre: "Máquina de aductores", dia: 4, orden: 8,
    seriesPlan: 3, repsPlan: "15-20", rpePlan: 9, descansoSeg: 60,
    notaTecnica: "Ya lo maxeas. Añade pausa de 2 seg en la contracción.",
    esAncla: false, restriccion: null, claveProgresion: null,
  },
  {
    id: 43, nombre: "Máquina de abductores", dia: 4, orden: 9,
    seriesPlan: 3, repsPlan: "15-20", rpePlan: 9, descansoSeg: 60,
    notaTecnica: "Glúteo medio. Lo que estabiliza la rodilla al aterrizar en baloncesto.",
    esAncla: false, restriccion: null, claveProgresion: null,
  },
  {
    id: 44, nombre: "Elevación de talones de pie o sentado", dia: 4, orden: 10,
    seriesPlan: 4, repsPlan: "12-15", rpePlan: 9, descansoSeg: 45,
    notaTecnica: "Pausa de 1 seg arriba y abajo.",
    esAncla: false, restriccion: null, claveProgresion: null,
  },
  {
    id: 45, nombre: "Press Pallof + plancha lateral", dia: 4, orden: 11,
    seriesPlan: 3, repsPlan: "12/lado + 40 seg", rpePlan: 8, descansoSeg: 45,
    notaTecnica: "Core sin flexión lumbar.",
    esAncla: false, restriccion: null, claveProgresion: null,
  },
  {
    id: 46, nombre: "CARDIO: caminata inclinada 15 min o bicicleta", dia: 4, orden: 12,
    seriesPlan: null, repsPlan: "15 min", rpePlan: null, descansoSeg: null,
    notaTecnica: "NO correr después de pierna. Mañana es ayuno y descanso: deja que la rodilla se recupere.",
    esAncla: false, restriccion: null, claveProgresion: null,
  },
]
