import type { BloqueHorario } from '../../dominio/tipos'

/** Hoja HORARIO — la semana bloque por bloque, cuadrada contra el calendario real. */
export const HORARIO: BloqueHorario[] = [
  { id: 1, dia: 1, hora: "05:00", actividad: "Despertar", detalle: "500 ml agua + 5 g creatina + electrolito sin calorías", bloque: "Bloque 1: arranque" },
  { id: 2, dia: 1, hora: "05:05", actividad: "Cama + bulto", detalle: "Cama tendida. El bulto se prepara la NOCHE anterior; aquí solo lo verificas.", bloque: "" },
  { id: 3, dia: 1, hora: "05:10", actividad: "Briefing de mercado", detalle: "10 min: cierre asiático, futuros US, DXY, WTI, oro, noticias BCRD. Lo lees, no lo estudias.", bloque: "" },
  { id: 4, dia: 1, hora: "05:25", actividad: "Salida a Body Shop", detalle: "", bloque: "" },
  { id: 5, dia: 1, hora: "05:35", actividad: "GYM — Día 1", detalle: "55 min fuerza + 15 min cardio Z2 (ver hoja GYM)", bloque: "Bloque 2: cuerpo" },
  { id: 6, dia: 1, hora: "06:50", actividad: "Regreso a casa", detalle: "", bloque: "" },
  { id: 7, dia: 1, hora: "07:00", actividad: "Baño + desayuno", detalle: "Desayuno post-entreno del menú (día ENTRENO)", bloque: "" },
  { id: 8, dia: 1, hora: "07:45", actividad: "Salida al trabajo", detalle: "", bloque: "" },
  { id: 9, dia: 1, hora: "08:00", actividad: "Pre-Market Analysis", detalle: "Ya en tu calendario", bloque: "Bloque 3: trabajo" },
  { id: 10, dia: 1, hora: "08:30", actividad: "Trabajo — Bloque 1", detalle: "FINTEL", bloque: "" },
  { id: 11, dia: 1, hora: "12:30", actividad: "Almuerzo", detalle: "Comida principal del día. Pesar antes de servir.", bloque: "" },
  { id: 12, dia: 1, hora: "14:00", actividad: "Trabajo — Bloque 2", detalle: "FINTEL", bloque: "" },
  { id: 13, dia: 1, hora: "16:55", actividad: "ROSARIO", detalle: "20 min antes de salir. Es un bloque, no un hueco.", bloque: "Bloque 4: alma" },
  { id: 14, dia: 1, hora: "17:20", actividad: "Merienda", detalle: "Whey + pan integral + fruta", bloque: "" },
  { id: 15, dia: 1, hora: "19:00", actividad: "BALONCESTO", detalle: "3 lunes al mes. El 4º lunes: estudio 19:45-21:45 y a dormir temprano.", bloque: "Bloque 5: PM" },
  { id: 16, dia: 1, hora: "21:15", actividad: "Cena", detalle: "Menú día ENTRENO", bloque: "" },
  { id: 17, dia: 1, hora: "21:45", actividad: "Estudio CFI-FMVA", detalle: "1h (día corto por baloncesto). Se compensa el domingo.", bloque: "" },
  { id: 18, dia: 1, hora: "22:45", actividad: "Lectura 15 min + oración de la noche", detalle: "", bloque: "" },
  { id: 19, dia: 1, hora: "23:00", actividad: "Dormir", detalle: "≈6h. Es el día más corto de la semana, por diseño.", bloque: "" },
  { id: 20, dia: 2, hora: "05:00", actividad: "Despertar", detalle: "Agua + creatina + electrolito", bloque: "Bloque 1" },
  { id: 21, dia: 2, hora: "05:05", actividad: "Cama + bulto", detalle: "", bloque: "" },
  { id: 22, dia: 2, hora: "05:10", actividad: "Briefing de mercado", detalle: "10 min", bloque: "" },
  { id: 23, dia: 2, hora: "05:35", actividad: "GYM — Día 2", detalle: "55 min fuerza + 15 min cardio", bloque: "Bloque 2" },
  { id: 24, dia: 2, hora: "07:00", actividad: "Baño + desayuno", detalle: "", bloque: "" },
  { id: 25, dia: 2, hora: "08:00", actividad: "Pre-Market Analysis", detalle: "", bloque: "Bloque 3" },
  { id: 26, dia: 2, hora: "08:30", actividad: "Trabajo — Bloque 1", detalle: "FINTEL", bloque: "" },
  { id: 27, dia: 2, hora: "12:30", actividad: "Almuerzo", detalle: "", bloque: "" },
  { id: 28, dia: 2, hora: "14:00", actividad: "Trabajo — Bloque 2", detalle: "FINTEL", bloque: "" },
  { id: 29, dia: 2, hora: "16:55", actividad: "ROSARIO", detalle: "20 min", bloque: "Bloque 4" },
  { id: 30, dia: 2, hora: "18:30", actividad: "MISA — Church SMP", detalle: "Ya en tu calendario. Martes es misa fija.", bloque: "" },
  { id: 31, dia: 2, hora: "19:35", actividad: "Cena", detalle: "Menú día ENTRENO", bloque: "Bloque 5" },
  { id: 32, dia: 2, hora: "19:50", actividad: "Estudio CFI-FMVA / SIMV", detalle: "2h", bloque: "" },
  { id: 33, dia: 2, hora: "21:50", actividad: "Lectura 20 min", detalle: "", bloque: "" },
  { id: 34, dia: 2, hora: "22:15", actividad: "Baño + preparar bulto + oración de la noche", detalle: "", bloque: "" },
  { id: 35, dia: 2, hora: "22:30", actividad: "Dormir", detalle: "≈6.5h", bloque: "" },
  { id: 36, dia: 3, hora: "05:00", actividad: "Despertar", detalle: "Agua + creatina + electrolito", bloque: "Bloque 1" },
  { id: 37, dia: 3, hora: "05:05", actividad: "Cama + bulto", detalle: "", bloque: "" },
  { id: 38, dia: 3, hora: "05:10", actividad: "Briefing de mercado", detalle: "10 min", bloque: "" },
  { id: 39, dia: 3, hora: "05:35", actividad: "GYM — Día 3", detalle: "Sesión más corta (50 min). El cardio de hoy es softball + natación.", bloque: "Bloque 2" },
  { id: 40, dia: 3, hora: "07:00", actividad: "Baño + desayuno", detalle: "", bloque: "" },
  { id: 41, dia: 3, hora: "08:00", actividad: "Pre-Market Analysis", detalle: "", bloque: "Bloque 3" },
  { id: 42, dia: 3, hora: "08:30", actividad: "Trabajo — Bloque 1", detalle: "FINTEL", bloque: "" },
  { id: 43, dia: 3, hora: "12:30", actividad: "Almuerzo", detalle: "", bloque: "" },
  { id: 44, dia: 3, hora: "14:00", actividad: "Trabajo — Bloque 2", detalle: "FINTEL", bloque: "" },
  { id: 45, dia: 3, hora: "16:55", actividad: "ROSARIO", detalle: "20 min (miércoles no hay misa vespertina)", bloque: "Bloque 4" },
  { id: 46, dia: 3, hora: "17:30", actividad: "SOFTBALL — Centro Español", detalle: "Swing abierto. Ya en tu calendario.", bloque: "Bloque 5" },
  { id: 47, dia: 3, hora: "18:50", actividad: "NATACIÓN — Centro Español", detalle: "30 min. Cierra 9 PM, tienes margen.", bloque: "" },
  { id: 48, dia: 3, hora: "19:40", actividad: "Cena", detalle: "Menú día ENTRENO", bloque: "" },
  { id: 49, dia: 3, hora: "20:00", actividad: "Estudio CFI-FMVA", detalle: "2h", bloque: "" },
  { id: 50, dia: 3, hora: "22:00", actividad: "Lectura 20 min + oración de la noche", detalle: "", bloque: "" },
  { id: 51, dia: 3, hora: "22:30", actividad: "Dormir", detalle: "≈6.5h", bloque: "" },
  { id: 52, dia: 4, hora: "05:00", actividad: "Despertar", detalle: "Agua + creatina + electrolito", bloque: "Bloque 1" },
  { id: 53, dia: 4, hora: "05:05", actividad: "Cama + bulto", detalle: "", bloque: "" },
  { id: 54, dia: 4, hora: "05:10", actividad: "Briefing de mercado", detalle: "10 min", bloque: "" },
  { id: 55, dia: 4, hora: "05:35", actividad: "GYM — Día 4 PIERNAS", detalle: "15 min movilidad/pliometría + 50 min fuerza. Cardio de hoy: caminata inclinada 15 min, NO correr.", bloque: "Bloque 2" },
  { id: 56, dia: 4, hora: "07:05", actividad: "Baño + desayuno", detalle: "", bloque: "" },
  { id: 57, dia: 4, hora: "08:00", actividad: "Pre-Market Analysis", detalle: "", bloque: "Bloque 3" },
  { id: 58, dia: 4, hora: "08:30", actividad: "Trabajo — Bloque 1", detalle: "FINTEL", bloque: "" },
  { id: 59, dia: 4, hora: "12:30", actividad: "Almuerzo", detalle: "Día de mayor carga de carbohidratos de la semana.", bloque: "" },
  { id: 60, dia: 4, hora: "14:00", actividad: "Trabajo — Bloque 2", detalle: "FINTEL", bloque: "" },
  { id: 61, dia: 4, hora: "16:55", actividad: "ROSARIO", detalle: "20 min", bloque: "Bloque 4" },
  { id: 62, dia: 4, hora: "18:30", actividad: "MISA — Church SMP", detalle: "2º jueves del mes: Adora y Confía, Centro Bellarmino (verificar hora).", bloque: "" },
  { id: 63, dia: 4, hora: "19:35", actividad: "Cena", detalle: "Menú día ENTRENO. Última comida antes del ayuno del viernes.", bloque: "Bloque 5" },
  { id: 64, dia: 4, hora: "19:50", actividad: "Estudio CFI-FMVA / SIMV", detalle: "2h", bloque: "" },
  { id: 65, dia: 4, hora: "21:50", actividad: "Lectura 20 min", detalle: "", bloque: "" },
  { id: 66, dia: 4, hora: "22:30", actividad: "Dormir", detalle: "≈6.5h", bloque: "" },
  { id: 67, dia: 5, hora: "05:00", actividad: "Despertar", detalle: "Solo agua + electrolito sin calorías. Sin creatina hoy (se retoma sábado).", bloque: "Bloque 1" },
  { id: 68, dia: 5, hora: "05:05", actividad: "Cama + bulto", detalle: "", bloque: "" },
  { id: 69, dia: 5, hora: "05:10", actividad: "Briefing de mercado", detalle: "10 min", bloque: "" },
  { id: 70, dia: 5, hora: "05:30", actividad: "Caminata 40-50 min", detalle: "Zona 2, conversacional. Puedes rezar el rosario aquí y liberar la tarde.", bloque: "Bloque 2" },
  { id: 71, dia: 5, hora: "06:40", actividad: "Baño", detalle: "Sin desayuno. Café negro permitido.", bloque: "" },
  { id: 72, dia: 5, hora: "08:00", actividad: "Pre-Market Analysis", detalle: "", bloque: "Bloque 3" },
  { id: 73, dia: 5, hora: "08:30", actividad: "Trabajo — Bloque 1", detalle: "FINTEL. Ten 2 L de agua en el escritorio, visibles.", bloque: "" },
  { id: 74, dia: 5, hora: "12:30", actividad: "Hora de comida = hora de oración", detalle: "No comes. Usa los 30 min para lectura espiritual y sal a caminar.", bloque: "" },
  { id: 75, dia: 5, hora: "14:00", actividad: "Trabajo — Bloque 2", detalle: "FINTEL", bloque: "" },
  { id: 76, dia: 5, hora: "18:30", actividad: "MISA — Church SMP", detalle: "1er viernes: Sagrado Corazón, noviciado jesuita.", bloque: "Bloque 4" },
  { id: 77, dia: 5, hora: "19:45", actividad: "CENA DE RUPTURA", detalle: "≈24h desde la cena del jueves. Comida normal, NO atracón: proteína + almidón + vegetales.", bloque: "Bloque 5" },
  { id: 78, dia: 5, hora: "20:15", actividad: "Estudio CFI-FMVA", detalle: "2h", bloque: "" },
  { id: 79, dia: 5, hora: "22:15", actividad: "Lectura + oración de la noche", detalle: "", bloque: "" },
  { id: 80, dia: 5, hora: "23:00", actividad: "Dormir", detalle: "≈7h. Día de mayor recuperación.", bloque: "" },
  { id: 81, dia: 6, hora: "06:30", actividad: "Despertar", detalle: "Agua + creatina", bloque: "Bloque 1" },
  { id: 82, dia: 6, hora: "06:40", actividad: "Cama + revisión semanal", detalle: "15 min: pesarte, cerrar la BITACORA de la semana, mirar el DASHBOARD.", bloque: "" },
  { id: 83, dia: 6, hora: "07:00", actividad: "Desayuno", detalle: "", bloque: "" },
  { id: 84, dia: 6, hora: "07:45", actividad: "Carrera 40-50 min", detalle: "El día que sí corres largo. Zona 2.", bloque: "Bloque 2" },
  { id: 85, dia: 6, hora: "09:00", actividad: "Compras de la semana", detalle: "Lista de ALIMENTOS. Ir con lista, no improvisar.", bloque: "Bloque 3" },
  { id: 86, dia: 6, hora: "11:00", actividad: "Estudio SIMV", detalle: "1-2h. Corredor de Valores tiene prioridad los fines de semana.", bloque: "" },
  { id: 87, dia: 6, hora: "13:00", actividad: "Almuerzo", detalle: "Menú día LIGERO", bloque: "" },
  { id: 88, dia: 6, hora: "16:00", actividad: "BALONCESTO — PUCMM", detalle: "Ya en tu calendario", bloque: "Bloque 4" },
  { id: 89, dia: 6, hora: "18:30", actividad: "MISA", detalle: "Church SMP 18:30. 2º sábado: San Ramón 19:00. 3er sábado: San Ramón, Jóvenes en Cristo.", bloque: "" },
  { id: 90, dia: 6, hora: "20:00", actividad: "Cena", detalle: "Menú día LIGERO", bloque: "Bloque 5" },
  { id: 91, dia: 6, hora: "21:00", actividad: "Tiempo libre / social", detalle: "Este bloque es a propósito. Un plan sin respiro no dura 12 semanas.", bloque: "" },
  { id: 92, dia: 6, hora: "23:00", actividad: "Dormir", detalle: "≈7.5h", bloque: "" },
  { id: 93, dia: 7, hora: "07:00", actividad: "Despertar", detalle: "Sin alarma agresiva. Agua + creatina.", bloque: "Bloque 1" },
  { id: 94, dia: 7, hora: "07:30", actividad: "Lavado de ropa y sábanas", detalle: "Poner la lavadora antes de misa; tender al regreso.", bloque: "Bloque 2" },
  { id: 95, dia: 7, hora: "10:30", actividad: "MISA", detalle: "10:30 AM o 12:00 M. 3er domingo: San Martín 10:00 AM.", bloque: "Bloque 3" },
  { id: 96, dia: 7, hora: "12:30", actividad: "Almuerzo familiar", detalle: "Día flexible: si hay comida en familia, disfrútala y ajusta la cena.", bloque: "" },
  { id: 97, dia: 7, hora: "14:30", actividad: "MEAL PREP", detalle: "2h. Cocinar pollo, arroz, batata y vegetales para Lu-Mi. Pesar y guardar en porciones.", bloque: "Bloque 4" },
  { id: 98, dia: 7, hora: "16:30", actividad: "Estudio CFI-FMVA + SIMV", detalle: "3h. Es el bloque más largo de la semana: aquí recuperas lo que el lunes te quita.", bloque: "" },
  { id: 99, dia: 7, hora: "19:30", actividad: "Cena", detalle: "Menú día LIGERO", bloque: "Bloque 5" },
  { id: 100, dia: 7, hora: "20:30", actividad: "Planificación de la semana", detalle: "30 min: llenar tipos de día en BITACORA, revisar calendario litúrgico del mes, preparar bulto del lunes.", bloque: "" },
  { id: 101, dia: 7, hora: "21:30", actividad: "Lectura", detalle: "Aquí va el libro que quieres terminar, no el que quieres empezar.", bloque: "" },
  { id: 102, dia: 7, hora: "23:00", actividad: "Dormir", detalle: "≈6h antes del lunes 5:00. Considera 22:30.", bloque: "" },
]
